// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeterisDeviceServer.Database;

namespace VeterisDeviceServer.Migrations
{
    [DbContext(typeof(DeviceServerContext))]
    [Migration("20190323072806_Translations")]
    partial class Translations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview3.19153.1");

            modelBuilder.Entity("VeterisDeviceServer.Database.Models.SerializedDeviceConfiguration", b =>
                {
                    b.Property<string>("DeviceSerialNumberId")
                        .HasColumnName("id");

                    b.Property<string>("SerializedConfiguration")
                        .HasColumnName("serialized");

                    b.HasKey("DeviceSerialNumberId");

                    b.ToTable("serialized_device_config");
                });

            modelBuilder.Entity("VeterisDeviceServer.Database.Models.SerializedDeviceTranslation", b =>
                {
                    b.Property<string>("DeviceSerialNumberId")
                        .HasColumnName("id");

                    b.Property<string>("SerializedTranslation")
                        .HasColumnName("serialized");

                    b.HasKey("DeviceSerialNumberId");

                    b.ToTable("serialized_device_trans");
                });
#pragma warning restore 612, 618
        }
    }
}
