// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeterisDeviceServer.Database;

namespace VeterisDeviceServer.Migrations
{
    [DbContext(typeof(DeviceServerContext))]
    partial class DeviceServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview3.19153.1");

            modelBuilder.Entity("VeterisDeviceServer.Database.Models.SerializedDeviceConfiguration", b =>
                {
                    b.Property<string>("DeviceSerialNumberId")
                        .HasColumnName("id");

                    b.Property<string>("SerializedConfiguration")
                        .HasColumnName("serialized");

                    b.HasKey("DeviceSerialNumberId");

                    b.ToTable("serialized_device_config");
                });

            modelBuilder.Entity("VeterisDeviceServer.Database.Models.SerializedDeviceTranslation", b =>
                {
                    b.Property<string>("DeviceSerialNumberId")
                        .HasColumnName("id");

                    b.Property<string>("SerializedTranslation")
                        .HasColumnName("serialized");

                    b.HasKey("DeviceSerialNumberId");

                    b.ToTable("serialized_device_trans");
                });

            modelBuilder.Entity("VeterisDeviceServer.Database.Models.ServerUserAccess", b =>
                {
                    b.Property<string>("Identifier")
                        .HasColumnName("id");

                    b.Property<int>("Role")
                        .HasColumnName("role");

                    b.Property<string>("ServerIdentifier")
                        .HasColumnName("server_identifier");

                    b.Property<string>("UserIdentifier")
                        .HasColumnName("user_identifier");

                    b.HasKey("Identifier");

                    b.ToTable("ServerUserAccesses");
                });
#pragma warning restore 612, 618
        }
    }
}
